name: GHCR-Action
description: This is a opinionated workflow to build and upload your docker image to the GitHub Container Registry.
author: André Kuhlmann
branding:
  icon: anchor
  color: gray-dark

inputs:
  token:
    description: The GitHub token to interact with the registry. Normally 'secrets.GITHUB_TOKEN'
    required: true
  build-args:
    description: (Optional) List of build-time variables
    required: false
  secrets:
    description: (Optional) List of secrets
    required: false
  dockerfile: # New input for dockerfile path
    description: Path to the Dockerfile (defaults to Dockerfile)
    default: Dockerfile # Set default value if not provided
  image-name-overwrite:
    description: (Optional) Name of the image to build
    required: false
  platforms:
    description: (Optional) The platforms you want to compile the docker images for. Defaults to linux/amd64 and linux/arm64
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: false # default
        submodules: false # default

    - name: Repository Variable to Lowercase
      id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        github-token:
          ${{ inputs.token }}
          # use image-name overwrite before using steps.string.outputs.lowercase
        images: ghcr.io/${{ inputs.image-name-overwrite || steps.string.outputs.lowercase }}
        tags: |
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: . # Use current directory as context
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}
        file: ${{ inputs.dockerfile }} # Use provided dockerfile path
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
